### ISSUE TITLE
Export currently internal functions

### ISSUE THREAD

**Issue by eblondel** [gaborcsardi/dotenv#11]
Could we export the below functions?
* `ignore_comments`
* `ignore_empty_lines`
* `parse_dot_line`
In https://github.com/r-geoflow/geoflow/issues/295 I needed to re-use these fonctions to unload workflow environment, using `:::`, but I now get a note doing R CMD checks. From the `:::` documentation, it's not a good best practice and it's suggested to contact maintainer to consider exporting the concerned functions.

Thanks in advance

**Comment by eblondel** [comment]
@gaborcsardi coming back on this, as it is blocker for [geoflow](https://github.com/r-geoflow/geoflow) build, where we are now calling these internal functions with `...`. Would you be in favor of adding this? Let me know, of course I can send a PR for exports/docs to add.
Many thanks in advance

**Comment by gaborcsardi** [comment]
These are pretty small functions, feel free to copy them in your package.

**Comment by eblondel** [comment]
Thanks!
