### ISSUE TITLE
Leading whitespace results in errors

### ISSUE THREAD

**Issue by keen99** [gaborcsardi/dotenv#3]
leading whitespace in configs consumed by dotenv results in errors.  (of course, leading whitespace is perfectly valid in even posix sh. :) )  

    Dotenv::FormatError: Line "  RL_EMAIL=\"david.raistrick@...\"" doesn't match format

Also - that error message escapes the quotes in the line, instead of printing them literally - might be better to format that differently? 

Happy to provide traceback - and I'll try to PR this if I get time.

dotenv (2.1.1)

**Comment by gaborcsardi** [comment]
> dotenv (2.1.1)

**This** `dotenv`'s latest version is 1.0.1. Maybe wrong repo?

**Comment by keen99** [comment]
huh, perhaps so!  sorry about that. :)

**Comment by keen99** [comment]
...perhaps a README and or project description to mention that this dotenv is for R... ? :)

**Comment by gaborcsardi** [comment]
OK, I added it to the "title" on top. The README mentions it, actually.
